# Conhecendo o conjunto de dados

I - Importar as bibliotecas.

In [154]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

II - Carregar o arquivo CSV.

In [155]:
df = pd.read_csv("Melhores_filmes_e_séries_de_TVIMDb.csv")

III - Exibir as primeiras e últimas linhas.

In [156]:
df.head()

,title,titleType,genres,numVotes,year,averageRating
0,The Shawshank Redemption,movie,Drama,3185932,1994,9.3
1,The Dark Knight,movie,"Action,Crime,Drama",3165032,2008,9.1
2,Inception,movie,"Action,Adventure,Sci-Fi",2814573,2010,8.8
3,Game of Thrones,tvSeries,"Action,Adventure,Drama",2611980,2011,9.2
4,Breaking Bad,tvSeries,"Crime,Drama,Thriller",2611328,2008,9.5

In [157]:
df.tail()

,title,titleType,genres,numVotes,year,averageRating
9994,Blood & Gold,movie,"Action,Drama,War",20178,2023,6.5
9995,Santa Claus Is Comin' to Town,tvMovie,"Adventure,Animation,Comedy",20176,1970,7.7
9996,The Tonight Show Starring Jimmy Fallon,tvSeries,"Comedy,Music,Talk-Show",20176,2014,7.0
9997,Come Play,movie,"Drama,Horror,Mystery",20172,2020,5.8
9998,Holiday,movie,"Comedy,Romance",20171,1938,7.7

IV - Identificar o número de linhas e colunas.

In [158]:
df.shape

(9999, 6)

V - Verificar os tipos de dados de cada coluna.

In [159]:
df.dtypes

title                str
titleType            str
genres               str
numVotes           int64
year               int64
averageRating    float64
dtype: object

Alteração nos nomes das colunas e criação de um  novo dataframe que tem os nomes das colunas em português.

In [160]:
df_renomeado = df.rename(columns={
    'title':'Titulo', 
    'titleType':'Categoria', 
    'genres':'Generos', 
    'numVotes':'Numero_Votos', 
    'year':'Ano', 
    'averageRating':'Media_Avaliacao'
})

In [161]:
df_renomeado.head()

,Titulo,Categoria,Generos,Numero_Votos,Ano,Media_Avaliacao
0,The Shawshank Redemption,movie,Drama,3185932,1994,9.3
1,The Dark Knight,movie,"Action,Crime,Drama",3165032,2008,9.1
2,Inception,movie,"Action,Adventure,Sci-Fi",2814573,2010,8.8
3,Game of Thrones,tvSeries,"Action,Adventure,Drama",2611980,2011,9.2
4,Breaking Bad,tvSeries,"Crime,Drama,Thriller",2611328,2008,9.5

# Qualidade dos dados

I - Verificar valores nulos.

In [162]:
print(df_renomeado.isnull().sum())

np.where(df.isnull())

Titulo             0
Categoria          0
Generos            1
Numero_Votos       0
Ano                0
Media_Avaliacao    0
dtype: int64

(array([4841]), array([2]))

II - Verificar valores duplicados.

In [163]:
df_renomeado.duplicated().sum()

np.int64(0)

III - Identificar possíveis inconsistências.

In [164]:
print(df_renomeado[df_renomeado["Numero_Votos"] < 0])
print(df_renomeado[(df_renomeado["Media_Avaliacao"] < 0) | (df_renomeado["Media_Avaliacao"] > 10)])
print(df_renomeado["Categoria"].unique())
print(df_renomeado["Generos"].unique())

Empty DataFrame
Columns: [Titulo, Categoria, Generos, Numero_Votos, Ano, Media_Avaliacao]
Index: []
Empty DataFrame
Columns: [Titulo, Categoria, Generos, Numero_Votos, Ano, Media_Avaliacao]
Index: []
<StringArray>
[       'movie',     'tvSeries', 'tvMiniSeries',    'tvSpecial',
      'tvMovie',        'video',    'videoGame',        'short',
      'tvShort']
Length: 9, dtype: str
<StringArray>
[                   'Drama',       'Action,Crime,Drama',
  'Action,Adventure,Sci-Fi',   'Action,Adventure,Drama',
     'Crime,Drama,Thriller',   'Adventure,Drama,Sci-Fi',
            'Drama,Romance',              'Crime,Drama',
            'Action,Sci-Fi',  'Adventure,Drama,Fantasy',
 ...
   'Family,Fantasy,Musical',     'Comedy,Crime,History',
  'Drama,Horror,Reality-TV',    'Crime,Sci-Fi,Thriller',
    'Action,Horror,Romance',      'Comedy,Horror,Music',
             'Action,Short',  'Crime,Documentary,Sport',
 'Animation,Fantasy,Horror',    'Action,Horror,Western']
Length: 466, dtype: str

IV - Realizar a limpeza, se necessário.

In [165]:
#substituir o valor nulo por um texto
df_renomeado["Generos"] = df_renomeado["Generos"].fillna("Desconhecido")

print(df_renomeado.isnull().sum())

Titulo             0
Categoria          0
Generos            0
Numero_Votos       0
Ano                0
Media_Avaliacao    0
dtype: int64

# Estatísticas descritivas

In [166]:
print("Principais estatísticas\n", df_renomeado.describe(), "\n")

print(f"Mediana")
print(f"Número de votos: {np.median(df_renomeado["Numero_Votos"])}")
print(f"Ano: {np.median(df_renomeado["Ano"])}")
print(f"Média de avaliações: {np.median(df_renomeado["Media_Avaliacao"])}\n")

print("Moda")
df_renomeado.mode()

Principais estatísticas
        Numero_Votos         Ano  Media_Avaliacao
count  9.999000e+03  9999.00000      9999.000000
mean   1.215959e+05  2005.50495         6.849405
std    2.002060e+05    16.87822         1.046733
min    2.017100e+04  1902.00000         1.000000
25%    3.065550e+04  1999.00000         6.200000
50%    5.417300e+04  2010.00000         6.900000
75%    1.228770e+05  2018.00000         7.600000
max    3.185932e+06  2026.00000         9.800000

Mediana
Número de votos: 54173.0
Ano: 2010.0
Média de avaliações: 6.9

Moda

,Titulo,Categoria,Generos,Numero_Votos,Ano,Media_Avaliacao
0,Beauty and the Beast,movie,"Comedy,Drama,Romance",20293,2018.0,6.7
1,Dracula,NaN,NaN,20386,NaN,NaN
2,NaN,NaN,NaN,20726,NaN,NaN
3,NaN,NaN,NaN,20803,NaN,NaN
4,NaN,NaN,NaN,21206,NaN,NaN
5,NaN,NaN,NaN,21924,NaN,NaN
6,NaN,NaN,NaN,22025,NaN,NaN
7,NaN,NaN,NaN,22498,NaN,NaN
8,NaN,NaN,NaN,22655,NaN,NaN
9,NaN,NaN,NaN,22724,NaN,NaN
10,NaN,NaN,NaN,23286,NaN,NaN
11,NaN,NaN,NaN,23455,NaN,NaN
12,NaN,NaN,NaN,23916,NaN,NaN
13,NaN,NaN,NaN,24219,NaN,NaN
14,NaN,NaN,NaN,24706,NaN,NaN
15,NaN,NaN,NaN,24846,NaN,NaN
16,NaN,NaN,NaN,25265,NaN,NaN
17,NaN,NaN,NaN,25677,NaN,NaN
18,NaN,NaN,NaN,25743,NaN,NaN
19,NaN,NaN,NaN,25938,NaN,NaN
20,NaN,NaN,NaN,26093,NaN,NaN
21,NaN,NaN,NaN,27585,NaN,NaN
22,NaN,NaN,NaN,27613,NaN,NaN
23,NaN,NaN,NaN,28421,NaN,NaN
24,NaN,NaN,NaN,28913,NaN,NaN
25,NaN,NaN,NaN,34715,NaN,NaN
26,NaN,NaN,NaN,56723,NaN,NaN
27,NaN,NaN,NaN,59920,NaN,NaN
28,NaN,NaN,NaN,84478,NaN,NaN

# Visualização dos dados